version: '3'
services:
  db:
    image: postgres:14
    container_name: 'crm'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_HOST=crm'
      - 'POSTGRES_USER=crm'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DATABASE=crm'
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-crm
    ports:
      - '6379:6379'
